volumes:
  postgres_data:
    driver: "local"

networks:
  auth_network:
    driver: "bridge"

services:
  # Serviço de Banco de Dados PostgreSQL
  postgres:
    image: postgres:alpine
    container_name: postgres_auth_service
    restart: always
    environment:
      - POSTGRES_DB=auth_service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    networks:
      - auth_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço de Autenticação (Spring Boot)
  auth-service:
    build:
      context: ./  # O contexto para o Dockerfile está no diretório atual
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/auth_service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - auth_network
    restart: always
